# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BDesign/BDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign || ORIG_REF_NAME==BDesign} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_processing_system7_0_0/BDesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_processing_system7_0_0 || ORIG_REF_NAME==BDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_clk_wiz_0_0/BDesign_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_clk_wiz_0_0 || ORIG_REF_NAME==BDesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_axi_uartlite_0_1/BDesign_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_axi_uartlite_0_1 || ORIG_REF_NAME==BDesign_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_axi_iic_0_0/BDesign_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_axi_iic_0_0 || ORIG_REF_NAME==BDesign_axi_iic_0_0} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_xbar_0/BDesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_xbar_0 || ORIG_REF_NAME==BDesign_xbar_0} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_ps7_0_axi_periph_0/BDesign_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==BDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_rst_ps7_0_100M_0/BDesign_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==BDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/BDesign/ip/BDesign_auto_pc_0/BDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BDesign_auto_pc_0 || ORIG_REF_NAME==BDesign_auto_pc_0} -quiet] -quiet

# XDC: e:/FPGA/FUSION/FUSION.gen/sources_1/bd/BDesign/BDesign_ooc.xdc
